#!/bin/sh
FLAGS="-I./expressions"
FLAGS="$FLAGS -I./compiler"
FLAGS="$FLAGS -I./dataset"
FLAGS="$FLAGS -I./vm"
FLAGS="$FLAGS -I./tests"
FLAGS="$FLAGS -Wno-format-security"
FLAGS="$FLAGS -g --std=c++20 -fopenmp -O3"

hipcc -c main.cc $FLAGS
hipcc -c expressions/expression.cc $FLAGS
hipcc -c expressions/binary.cc $FLAGS
hipcc -c compiler/bytecode.cc $FLAGS
hipcc -c compiler/compiler.cc $FLAGS
hipcc -c dataset/dataset.cc $FLAGS
hipcc -c vm/vm.hip $FLAGS
hipcc -c vm/vm_helper.hip $FLAGS
hipcc -c tests/testdata.cc $FLAGS

hipcc main.o \
      expression.o \
      binary.o \
      bytecode.o \
      compiler.o \
      dataset.o \
      vm.o \
      vm_helper.o \
      testdata.o \
      -o quicksr.exe $FLAGS

rm *.o