#!/bin/sh
FLAGS=""
FLAGS="$FLAGS -Wno-format-security"
FLAGS="$FLAGS -g --std=c++20 -fopenmp -O3"

hipcc -c main-inter.cc -o main-inter.o $FLAGS
hipcc -c main-intra.cc -o main-intra.o $FLAGS

hipcc -c expressions/expression.cc -o expressions/expression.o $FLAGS
hipcc -c expressions/binary.cc -o expressions/binary.o $FLAGS

hipcc -c compiler/ir.cc -o compiler/ir.o $FLAGS
hipcc -c compiler/compiler.cc -o compiler/compiler.o $FLAGS

hipcc -c intra-individual/dataset/dataset.cc -o intra-individual/dataset/dataset.o $FLAGS
hipcc -c intra-individual/vm/vm.hip -o intra-individual/vm/vm.o $FLAGS
hipcc -c intra-individual/program/program.cc -o intra-individual/program/program.o $FLAGS
hipcc -c intra-individual/runner.cc -o intra-individual/runner.o $FLAGS

hipcc -c inter-individual/dataset/dataset.cc -o inter-individual/dataset/dataset.o $FLAGS
hipcc -c inter-individual/compiler/programpopulation.cc -o inter-individual/compiler/programpopulation.o $FLAGS

hipcc -c tests/testdata.cc $FLAGS

hipcc main-intra.o \
      \
      expressions/expression.o \
      expressions/binary.o \
      \
      compiler/ir.o \
      compiler/compiler.o \
      \
      intra-individual/dataset/dataset.o \
      intra-individual/vm/vm.o \
      intra-individual/program/program.o \
      intra-individual/runner.o \
      \
      inter-individual/dataset/dataset.o \
      \
      testdata.o \
      -o quicksr.exe $FLAGS

rm *.o

rm compiler/*.o
rm expressions/*.o

rm intra-individual/program/*.o
rm intra-individual/dataset/*.o
rm intra-individual/vm/*.o
rm intra-individual/*.o

#rm inter-individual/compiler/*.o
rm inter-individual/dataset/*.o
#rm inter-individual/vm/*.o
#rm inter-individual/*.o
